# site settings
title: Nick S Iyer
subtitle: .me
email: nick.s.iyer@gmail.com
description: A website dedicated to code blogging,<br /> data science, machine learning, and more...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
seehere: Link to CV
#author:
#street_address:
#city:
#state:
#zip_code:
#country:
phone: (516) 426-6643

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/nicksiyer
gitlab_url:
googleplus_url:
instagram_url: https://www.instagram.com/toomuchgolf/
linkedin_url: https://www.linkedin.com/in/nicksiyer/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/nicksiyer

# build settings
markdown: kramdown

sass:
  style: compressed
