# Site settings
title: Nick S Iyer | Data Science Analyst
description: A blog on data science and analysis through projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.nicksiyer.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nick S Iyer
user_description: Data scientist and machine learning enthusiast with a curiousity for applications in fraud, healthcare, real estate and more. Check out the tools I commonly use and projects I've developed for my blog below. Born and raised in New York, I am a computer nerd, chef, and golfer at heart.
user_title: Data Science Analyst
email: nick.s.iyer@gmail.com
twitter_username: nicksiyer
github_username: nicksiyer
linkedin_username: nicksiyer
avatar: /assets/img/avatar.jpg
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: UA-106750457-1

# Post settings
img_path: /assets/img/blog

exclude: ['package.json', 'src' , 'node_modules']
