# Site settings
title: Nick S Iyer | Analyst
description: A blog on data science and analysis through projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.nicksiyer.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nick S Iyer
user_description: Started my journey with a B.S. in Mathematics & Actuarial Science from the State University of New York at Albany. Developed my technical abilities working for a daily fantasy sports publication and healthcare management organization. Recent graduate of Metis - a highly selective and immersive data science bootcamp. Currently looking for my next full time role merging my statistical learning knowledge with state-of-the-art implementation experience using cloud computing, Python and SQL. Born and raised in New York, I enjoy cooking at home on weekends and playing golf both competitively and recreationally.
user_title: Analyst
email: nick.s.iyer@gmail.com
twitter_username: nicksiyer
github_username: nicksiyer
linkedin_username: nicksiyer
avatar: /assets/img/avatar.jpg
img_path: /assets/img
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: UA-106750457-1

# Post settings
img_path: /assets/img/blog

exclude: ['package.json', 'src' , 'node_modules']
