# Site settings
title: Nick S Iyer | Data Science Analyst
description: A blog on data science and analysis through projects
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.nicksiyer.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nick S Iyer
user_description:
user_title: Data Science Analyst
email: nick.s.iyer@gmail.com
twitter_username: nicksiyer
github_username: nicksiyer
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: 106750457

exclude: ['package.json', 'src' , 'node_modules']
