# Site settings
title: Nick S. Iyer | Data Scientist
description: My portfolio of ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.nicksiyer.tech" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nick S. Iyer
user_description: B.S. in Mathematics & Actuarial Science from the State University of New York at Albany. Worked for numberfire, a daily fantasy sports publication, in DFS infancy. Moved into healthcare management, tracking metrics of patients and providers at ProHealth Care. Graduated from Metis bootcamp in 2017 and been working for The NPD Group, one of the top market research firms in the world. I specialize in processing and mining text data, NLP, and other statistical learning techniques. My state-of-the-art implementation experience using cloud computing, Python and SQL, turns problems into potential. Born and raised in New York, I enjoy cooking at home on weekends and playing golf both competitively and recreationally.
user_title: Data Scientist
email: nick.s.iyer@gmail.com
twitter_username: nicksiyer
github_username: nicksiyer
linkedin_username: nicksiyer
avatar: /assets/img/avatar.jpg
img_path: /assets/img
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: UA-106750457-1

# Post settings
img_path: /assets/img/blog

exclude: ['package.json', 'src' , 'node_modules']
