# Site settings
title: Data Science & Analytics
description: A blog about lorem ipsum dolor sit amet
baseurl: "/" # the subpath of your site, e.g. /blog
url: "www.nicksiyer.me" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: nicksiyer
user_description:
user_title: Software Developer
email: anon@anon.com
twitter_username: nicksiyer
github_username: nicksiyer
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
